### ISSUE TITLE
Gravity and Orbits Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-and-orbits#254]
## Design
- [x] **Sim folder and design doc created** (Date: 07/01/2013) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) with phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 07/01/2013)
- [x] **Design concept complete**  (Date: 07/03/2013)
- [x] **Wireframes complete** (Date: 07/11/2013) 
- [x] **Mockups complete** (Date: 10/07/2015) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 08/10/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 09/08/2016) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Compatible activities ([author spreadsheet](https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [x] Sim primer (Being tracked in #260)
  - [x] Verify credits
- [x] **Update [Gooru PhET URL tracker](https://docs.google.com/spreadsheets/d/19sffdKj9NdMuFdp3NcFeJmPyDY-3KsoM7Pbu84gUVtw/edit#gid=636879231)**
- [x] **Add to Edmodo**

## Implementation
- [x] **Sim repo created** (Date: 6/29/2007) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme file
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked to pull from rosetta to avoid conflicts.
- [x] **Initial development started** (Date: 6/29/2007)
- [x] **Sim feature complete** (Date: 01/24/2014) 
- [x] **Code review complete** (Date: 11/9/15) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 11/28/2016)
  - [x] Update repo README to published template

## QA
- [x] **Legacy sim tested for bugs**: issues reported in repo
- [x] **Dev testing complete** (Date: 10/31/2016) 
- [x] **First release candidate** (Date: 11/10/2016)
  - [x] Place in matrix in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
  - [x] Test matrix deemed complete

**Comment by jessegreenberg** [comment]
@ariel-phet @arouinfar when the sim is made visible on the site can you please let me know?  Once it is visible I need to update the third party licenses.

**Comment by arouinfar** [comment]
Will do @jessegreenberg!

**Comment by ariel-phet** [comment]
@jessegreenberg sim has been made visible.

**Comment by jessegreenberg** [comment]
Thanks - I'm missing an authorization code for the grunt task to generate the report.  Ill get it from another developer and try again.

**Comment by ariel-phet** [comment]
@arouinfar I think the remaining items are yours

**Comment by jessegreenberg** [comment]
Third party licenses have been reported for this sim's release.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. I will finish the remaining items this week (primer excluded).

**Comment by jessegreenberg** [comment]
@arouinfar @ariel-phet with #260 can this issue be closed?

**Comment by ariel-phet** [comment]
@jessegreenberg it looks like @arouinfar has not yet pasted interview notes into the design doc
