### ISSUE TITLE
Update Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#325]
The Teacher Tips were last updated in 2016 and could use some refreshing.

- [x] The grid dimensions should also be provided, as mentioned in #323 
- [x] Model updates, #302 
- [x] Kepler's 3rd Law, #275 
- [x] Objects are grabbable by their label, #338
- [x] Pan and Zoom

**Comment by arouinfar** [comment]
Updated tips have been uploaded, closing.
